### ISSUE TITLE
where can I get the sample data

### ISSUE THREAD

**Issue by witwall** [benadaba/Price-Optimisation#1]
thanks for the code, and could you tell me where can i get optimum_pricePOS.csv?

**Comment by benadaba** [comment]
Hi  Steven
sorry for the late reply.

sure you can download the dataset from here:

http://datapandas.com/index.php/2016/11/02/decision-tree-price-optimisation
-regression-tree/

regards
Bernard

**Comment by sidharth8338** [comment]
Please provide the dataset there is nothing in this url

**Comment by alitrack** [comment]
> Please provide the dataset there is nothing in this url

try http://datapandas.com/wp-content/uploads/2016/11/sample-data-for-price-optimisation-csv.csv
